

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  before_all do
    cocoapods
  end
	
  desc "Run test"
  lane :tests do
    run_tests 
  end
end
